spring.application.name=Acedemy
server.port=8081



spring.datasource.url=jdbc:mysql://localhost:3306/deltagamma?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=



spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# spring.datasource.url=jdbc:h2:mem:deltagamma-academy;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# spring.jpa.hibernate.ddl-auto=create-drop
# spring.jpa.show-sql=false

jwt.secret=RGVsdGFHYW1tYUFjYWRlbXlTdXBlclNlY3JldEtleUZvclN0dWRlbnRQbGF0Zm9ybTIwMjY=
jwt.expiration-ms=86400000


spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google
app.oauth2.frontend-redirect-base=http://localhost:5174

app.seed.enabled=true
